### ISSUE TITLE
Can't run ANCOMBC

### ISSUE THREAD

**Issue by mortonjt** [mortonjt/q2-ancombc#4]
See the README here : https://github.com/mortonjt/q2-ancombc/tree/main/q2_ancombc/tests

I'm having trouble running a ANCOM on a simple scenario.  If I run
`run_ancombc.R Rdata/input.biom.tsv Rdata/taxonomy.tsv Rdata/input.map.txt labels holm 0.9 1000 nation TRUE TRUE 1e-05 100 TRUE 0.05 TRUE output.summary.txt`

I get the following error

```
Error in `[.data.frame`(meta_data, , group) : undefined columns selected
Calls: ancombc -> data_prep -> unique -> [ -> [.data.frame
Execution halted
```

Not sure how to resolve this, since the error seems to be raised within ANCOMBC.

**Comment by mortonjt** [comment]
@mestaki @colinbrislawn , do you have thoughts on this?  I figured that I must have just fudged the way that I formatted the phyloseq objects.

**Comment by colinbrislawn** [comment]
Because you are grouping by 'nation', the [input.map.txt](https://github.com/mortonjt/q2-ancombc/blob/main/q2_ancombc/tests/Rdata/input.map.txt) needs a column called 'nation.'

Here's one way to add a fake 'nation' column with 🇲🇽 & 🇨🇦 
```R
sample_data(data) <- data %>%
  sample_data() %>% data.frame() %>%
  mutate(nation = case_when(
    (row_number() %% 5) == 0 ~ "Canada",
    TRUE ~ "Mexico")
  )

```

**Comment by mortonjt** [comment]
Hi @colinbrislawn thanks for your comment!  Looking over this more carefully, it seems so obvious :]
So its working now, adding docs in a sec.

**Comment by mestaki** [comment]
Glad this is resolved. Just as a heads up, I know there isn't another option atm but dependency on Phyloseq for this plugin is not ideal imo, it's a rather bulky package itself and historically has been infamous for installation issues (though admittedly, much much better these days). So this would of course be great as-is, but down the line it would be ideal to recode it without phyloseq. If I find some time I can try and do this, would be good practice for a first developing project.

**Comment by mortonjt** [comment]
Not sure how hard this would be.  Thoughts @FrederickHuangLin?

**Comment by FrederickHuangLin** [comment]
Thanks for your suggestion @mestaki, and thanks for letting me know @mortonjt!

The ANCOMBC R package was initially written without the dependency of phyloseq package (I have that source code in hand :)). The reason why we chose to add that dependency is that given the popularity of phyloseq package in the community, connecting ANCOMBC and phyloseq could further streamline the microbiome analysis workflow (from data operations,  analysis of diversities, to differential abundance analysis, etc.).

Additionally, ANCOMBC is still under development, more features will be added to the package. A stronger connection between ANCOMBC and phyloseq will be expected.

Best,
Huang

**Comment by mestaki** [comment]
Thanks @FrederickHuangLin! Just to be clear, I only meant removing the dependency for the q2-ANCOMBC version, not the stand-alone version in R. Integrating with Phyloseq is certainly super useful there and makes total sense given the future plans with it.
But who knows, maybe it will be super easy as a dependency in Q2 too, though as far as I know no other Q2 plugin has used it before. Let's see what happens, more of a 'heads up' than anything :P
